from abc import ABC, abstractmethod


class LLMProviderError(RuntimeError):
    """Raised when an LLM provider cannot return a usable completion."""


class LLMProvider(ABC):
    """Provider-neutral interface used by application services."""

    @abstractmethod
    def generate(self, system_prompt: str, user_prompt: str) -> str:
        """Return the text content generated by the configured model."""
