from abc import ABC, abstractmethod

from exceptions import LLMProviderError


class LLMProvider(ABC):
    """Provider-neutral interface used by application services."""

    @abstractmethod
    def generate(self, system_prompt: str, user_prompt: str) -> str:
        """Return the text content generated by the configured model."""
